spring:
  datasource:
    name: javaValidationdb
    url:  jdbc:mysql://localhost:3306/javaValidationdb?serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
server:  port: 9292